services:
  # Application container
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rule_engine_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  # Nginx web server container
  web:
    image: nginx:alpine
    container_name: rule_engine_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  # MySQL database container
  db:
    image: mysql:8.0
    container_name: rule_engine_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  # Mailhog email service container
  mailhog:
    image: mailhog/mailhog
    container_name: rule_engine_mailhog
    ports:
      - "${MAIL_PORT}:8025"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local
