name: Rule Engine CI/CD

on:
  push:
    branches:
      - deploy-ci-cd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx (for multi-platform builds)
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t vivek022/the-rule-engine:latest .
          docker push vivek022/the-rule-engine:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into Production Server and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PRODUCTION_SERVER }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/rule-engine
            docker pull vivek022/the-rule-engine:latest
            docker compose down
            docker compose up -d --build
            docker compose exec app php artisan migrate --force
        env:
          APP_KEY: $${{ secrets.APP_KEY }}
          MYSQL_DATABASE: $${{ secrets.DB_DATABASE }}
          MYSQL_USER: $${{ secrets.DB_USERNAME }}
          MYSQL_PASSWORD: $${{ secrets.DB_PASSWORD }}
          MYSQL_ROOT_PASSWORD: $${{ secrets.DB_ROOT_PASSWORD }}
          RABBITMQ_DEFAULT_PASS: $${{ secrets.RABBITMQ_PASSWORD }}
          RABBITMQ_DEFAULT_USER: $${{ secrets.RABBITMQ_USER }}
          SLACK_ALERT_WEBHOOK: $${{ secrets.SLACK_ALERT_WEBHOOK }}
